SAVE_TEXT_IMAGE_TO_DISK = False
FONT_SIZE = 20
FONT_SIZE_MIN = 20
FONT_SIZE_MAX = 20
IMG_WIDTH = 28
IMG_HEIGHT = 28

DATASET_DIR = 'data/train/characters/'
DATASET_FILE_NAME = 'dataset.csv'
DATASET_FILE = DATASET_DIR + DATASET_FILE_NAME
FONT_LIST = 'fonts/fonts.list'

CHARACTERS_SET = 'data/vi.characters.csv'

#SUM_SAMPLES = 105640
SUM_SAMPLES = 100
NO_LABEL = 190